apiVersion: apps/v1
kind: Deployment
metadata:
  name: lines-admin-nextjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lines-admin-nextjs
  template:
    metadata:
      labels:
        app: lines-admin-nextjs
    spec:
      containers:
      - name: lines-admin-nextjs
        image: gcr.io/lines-infra/lines_admin_front:v0.1.0
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"
        ports:
        - containerPort: 3000
